// Chapter 1 "La Route des Cendres" — webtoon scenes, staged like the
// prelude panels (lib/story.ts). Every scene has at least 5 panels.
import type { PreludePanel } from "@/lib/story";

/** Scene 1 — the Guild sends the hero to Bourg-Soleil, the Fox guides him. */
export const CH1_DEPART: PreludePanel[] = [
  {
    id: "ch1-guild",
    textKey: "story.chapter1.depart.s1",
    bg: ["#101A3E", "#2C4A9E"],
    glow: "#7EC8FF",
    effect: "summon",
    actors: [
      { emoji: "🏛️", x: 0, y: -110, size: 90, anim: "bob" },
      { emoji: "📜", x: -85, y: 15, size: 44, anim: "pulse", delay: 200 },
      { emoji: "🦸", x: 60, y: 60, size: 64, anim: "pulse" },
      { emoji: "🛡️", x: -20, y: 130, size: 36, anim: "pulse", delay: 400 },
      { emoji: "✨", x: 100, y: 140, size: 30, anim: "pulse", delay: 500 },
    ],
    bubble: { textKey: "story.chapter1.depart.b1", x: 0, y: -15 },
  },
  {
    id: "ch1-fox-guide",
    textKey: "story.chapter1.depart.s2",
    bg: ["#1B1206", "#54400E"],
    glow: "#FFD166",
    effect: "blessing",
    actors: [
      { emoji: "🦊", x: -40, y: -70, size: 84, anim: "bob" },
      { emoji: "🌪️", x: 45, y: -120, size: 40, anim: "spin", delay: 200 },
      { emoji: "🦸", x: 60, y: 60, size: 62, anim: "pulse" },
      { emoji: "✨", x: -95, y: 30, size: 32, anim: "pulse", delay: 350 },
      { emoji: "💫", x: 100, y: 150, size: 30, anim: "pulse", delay: 550 },
    ],
    bubble: { textKey: "story.chapter1.depart.b2", x: -30, y: 20 },
  },
  {
    id: "ch1-road",
    textKey: "story.chapter1.depart.s3",
    bg: ["#04121F", "#0E4D3A"],
    glow: "#4ADE80",
    effect: "calm",
    actors: [
      { emoji: "🌄", x: 0, y: -160, size: 64, anim: "pulse" },
      { emoji: "🌲", x: -100, y: -55, size: 46, anim: "bob" },
      { emoji: "🌲", x: 102, y: -40, size: 40, anim: "bob", delay: 300 },
      { emoji: "🦸", x: -30, y: 70, size: 62, anim: "bob" },
      { emoji: "🦊", x: 55, y: 95, size: 44, anim: "bob", delay: 200 },
      { emoji: "🛤️", x: 0, y: 160, size: 48, anim: "fade", delay: 400 },
    ],
  },
  {
    id: "ch1-omen",
    textKey: "story.chapter1.depart.s4",
    bg: ["#14142B", "#2E2A55"],
    glow: "#A78BFA",
    effect: "calm",
    actors: [
      { emoji: "🌫️", x: 0, y: -150, size: 70, anim: "fade" },
      { emoji: "🏘️", x: 0, y: -55, size: 56, anim: "fade", delay: 250 },
      { emoji: "🦊", x: -60, y: 90, size: 44, anim: "shake", delay: 150 },
      { emoji: "😟", x: 50, y: 80, size: 52, anim: "bob" },
      { emoji: "🌲", x: 105, y: 150, size: 38, anim: "bob", delay: 400 },
    ],
    bubble: { textKey: "story.chapter1.depart.b4", x: -25, y: 25 },
  },
  {
    id: "ch1-silhouette",
    textKey: "story.chapter1.depart.s5",
    bg: ["#1B0A2E", "#3A1D6E"],
    glow: "#F472B6",
    effect: "portal",
    actors: [
      { emoji: "🌫️", x: -80, y: -140, size: 56, anim: "fade" },
      { emoji: "👤", x: 0, y: -60, size: 80, anim: "fade", delay: 300 },
      { emoji: "❓", x: 55, y: -130, size: 36, anim: "pulse", delay: 500 },
      { emoji: "🦸", x: -70, y: 110, size: 56, anim: "pulse" },
      { emoji: "🦊", x: 60, y: 130, size: 42, anim: "shake", delay: 200 },
    ],
    bubble: { textKey: "story.chapter1.depart.b5", x: 30, y: 40 },
  },
];

/** Scene 2 — Bourg-Soleil stands intact but hollow; Gromak springs out. */
export const CH1_VILLAGE: PreludePanel[] = [
  {
    id: "ch1-gates",
    textKey: "story.chapter1.village.s1",
    bg: ["#101A3E", "#2C4A9E"],
    glow: "#7EC8FF",
    effect: "calm",
    actors: [
      { emoji: "🏘️", x: 0, y: -110, size: 90, anim: "fade" },
      { emoji: "🚪", x: 0, y: 0, size: 46, anim: "fade", delay: 250 },
      { emoji: "🦸", x: -70, y: 110, size: 56, anim: "bob" },
      { emoji: "👴", x: 5, y: 130, size: 44, anim: "bob", delay: 200 },
      { emoji: "🦊", x: 70, y: 115, size: 42, anim: "bob", delay: 400 },
    ],
  },
  {
    id: "ch1-hollow",
    textKey: "story.chapter1.village.s2",
    bg: ["#1B0A2E", "#3A1D6E"],
    glow: "#A78BFA",
    effect: "calm",
    actors: [
      { emoji: "🏚️", x: 0, y: -130, size: 70, anim: "fade" },
      { emoji: "😶", x: -90, y: 0, size: 44, anim: "fade", delay: 150 },
      { emoji: "😶", x: 0, y: 35, size: 44, anim: "fade", delay: 350 },
      { emoji: "😶", x: 90, y: 0, size: 44, anim: "fade", delay: 550 },
      { emoji: "🧠", x: 50, y: -80, size: 28, anim: "fade", delay: 700 },
    ],
  },
  {
    id: "ch1-tomir-lost",
    textKey: "story.chapter1.village.s3",
    bg: ["#14142B", "#2E2A55"],
    glow: "#FFD166",
    effect: "calm",
    actors: [
      { emoji: "👴", x: -30, y: -50, size: 72, anim: "shake" },
      { emoji: "💭", x: 50, y: -130, size: 48, anim: "fade", delay: 300 },
      { emoji: "🏚️", x: -90, y: 80, size: 50, anim: "bob", delay: 150 },
      { emoji: "🦸", x: 70, y: 110, size: 54, anim: "pulse" },
      { emoji: "💔", x: 20, y: 20, size: 30, anim: "pulse", delay: 500 },
    ],
    bubble: { textKey: "story.chapter1.village.b3", x: -20, y: 60 },
  },
  {
    id: "ch1-brigands",
    textKey: "story.chapter1.village.s4",
    bg: ["#1C0802", "#5E1B08"],
    glow: "#FB923C",
    effect: "attack",
    actors: [
      { emoji: "👺", x: -85, y: -90, size: 58, anim: "shake" },
      { emoji: "👺", x: 85, y: -75, size: 58, anim: "shake", delay: 200 },
      { emoji: "⚡", x: 0, y: -160, size: 40, anim: "fade", delay: 100 },
      { emoji: "🦸", x: 0, y: 90, size: 60, anim: "pulse" },
      { emoji: "🦊", x: -80, y: 130, size: 42, anim: "shake", delay: 300 },
    ],
  },
  {
    id: "ch1-gromak",
    textKey: "story.chapter1.village.s5",
    bg: ["#16030C", "#54101F"],
    glow: "#FF4D6D",
    effect: "attack",
    actors: [
      { emoji: "⚡", x: -105, y: -180, size: 42, anim: "fade" },
      { emoji: "👹", x: 0, y: -95, size: 112, anim: "shake" },
      { emoji: "⚡", x: 105, y: -165, size: 44, anim: "fade", delay: 320 },
      { emoji: "👺", x: -88, y: 50, size: 46, anim: "shake", delay: 150 },
      { emoji: "👺", x: 88, y: 60, size: 46, anim: "shake", delay: 300 },
      { emoji: "🦸", x: 0, y: 145, size: 58, anim: "pulse", delay: 200 },
    ],
    bubble: { textKey: "story.chapter1.village.b5", x: 0, y: 0 },
  },
];

/** Scene 3 — memories return; Tomir finds his home, the Fox joins the hero. */
export const CH1_OUTRO: PreludePanel[] = [
  {
    id: "ch1-light",
    textKey: "story.chapter1.outro.s1",
    bg: ["#1B1206", "#54400E"],
    glow: "#FFD166",
    effect: "blessing",
    actors: [
      { emoji: "☀️", x: 0, y: -150, size: 64, anim: "pulse" },
      { emoji: "✨", x: -95, y: -80, size: 34, anim: "pulse", delay: 200 },
      { emoji: "✨", x: 95, y: -70, size: 34, anim: "pulse", delay: 400 },
      { emoji: "🏘️", x: 0, y: 20, size: 80, anim: "bob" },
      { emoji: "🧠", x: 60, y: 130, size: 32, anim: "pulse", delay: 550 },
    ],
  },
  {
    id: "ch1-celebrate",
    textKey: "story.chapter1.outro.s2",
    bg: ["#101A3E", "#2C4A9E"],
    glow: "#7EC8FF",
    effect: "blessing",
    actors: [
      { emoji: "🎉", x: -100, y: -130, size: 40, anim: "pulse" },
      { emoji: "🎊", x: 100, y: -120, size: 40, anim: "pulse", delay: 300 },
      { emoji: "🥳", x: -85, y: 30, size: 46, anim: "bob", delay: 100 },
      { emoji: "😊", x: 0, y: 60, size: 46, anim: "bob", delay: 300 },
      { emoji: "🤗", x: 85, y: 30, size: 46, anim: "bob", delay: 500 },
      { emoji: "🦸", x: 0, y: 150, size: 56, anim: "pulse" },
    ],
  },
  {
    id: "ch1-restored",
    textKey: "story.chapter1.outro.s3",
    bg: ["#1B1206", "#54400E"],
    glow: "#FFD166",
    effect: "blessing",
    actors: [
      { emoji: "🏡", x: -90, y: -140, size: 50, anim: "bob" },
      { emoji: "👴", x: -55, y: 0, size: 52, anim: "bob" },
      { emoji: "👧", x: 35, y: 15, size: 44, anim: "bob", delay: 250 },
      { emoji: "💞", x: -8, y: -70, size: 36, anim: "pulse", delay: 400 },
      { emoji: "🥹", x: 100, y: 130, size: 38, anim: "bob", delay: 350 },
    ],
    bubble: { textKey: "story.chapter1.outro.b3", x: 0, y: 80 },
  },
  {
    id: "ch1-fox-joins",
    textKey: "story.chapter1.outro.s4",
    bg: ["#0B0E2A", "#3B1A55"],
    glow: "#FACC15",
    effect: "blessing",
    actors: [
      { emoji: "✨", x: -100, y: -170, size: 34, anim: "pulse" },
      { emoji: "🦊", x: -45, y: -60, size: 72, anim: "pulse" },
      { emoji: "🦸", x: 55, y: -50, size: 70, anim: "bob", delay: 200 },
      { emoji: "🌪️", x: -45, y: 55, size: 40, anim: "spin", delay: 300 },
      { emoji: "💫", x: 100, y: -150, size: 34, anim: "pulse", delay: 450 },
    ],
    bubble: { textKey: "story.chapter1.outro.b4", x: -40, y: 30 },
  },
  {
    id: "ch1-north",
    textKey: "story.chapter1.outro.s5",
    bg: ["#04121F", "#10395F"],
    glow: "#7EC8FF",
    effect: "portal",
    actors: [
      { emoji: "🧭", x: 0, y: -140, size: 56, anim: "pulse" },
      { emoji: "❄️", x: -90, y: -60, size: 40, anim: "fade", delay: 200 },
      { emoji: "🌊", x: 90, y: -50, size: 44, anim: "bob", delay: 350 },
      { emoji: "🦸", x: -45, y: 90, size: 58, anim: "bob" },
      { emoji: "🦊", x: 50, y: 105, size: 44, anim: "bob", delay: 250 },
    ],
    bubble: { textKey: "story.chapter1.outro.b5", x: 25, y: -10 },
  },
];
